title: TutorCruncher
email: info@tutorcruncher.com
description: TutorCruncher - Tuition management software with card payments, CRM, invoicing, payroll, scheduling, timesheets and more. Buy and get support.
baseurl: ""
url: "https://tutorcruncher.com"
source: site
exclude:
  - _posts/2000-01-01-blog-post-template.md
static: https://cdn1.tutorcruncher.com
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
