title: "TimeCruncher: Tutoring Management Software"
email: info@tutorcruncher.com
description: "TimeCruncher provides tutoring management software with card payments, CRM, invoicing, payroll, scheduling, timesheets and more. Buy and get support."
baseurl: ""
url: "https://tutorcruncher.com"
source: site
#static: https://cdn1.tutorcruncher.com
static: /static/
exclude:
  - _posts/2000-01-01-blog-post-template.md
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
