title: TutorCruncher - Tuition Management Software
email: info@tutorcruncher.com
description: Tuition management software with card payments, CRM, invoicing, payroll, scheduling, timesheets and more.
baseurl: ""
url: "https://tutorcruncher.com"
static: https://cdn1.tutorcruncher.com
exclude:
  - README.md
  - deploy.sh
  - bob_key.enc
  - Gemfile
  - Gemfile.lock
  - .travis.yml
  - .gitignore
  - generate_change_log.py
  - .bundle
  - vendor
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
